// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_top_bnn_top_Pipeline_L1_LOAD (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        sext_ln33,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_address0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_ce0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_we0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_d0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_address0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_ce0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_we0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_d0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_address0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_ce0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_we0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_d0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_address0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_ce0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_we0,
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [1023:0] m_axi_gmem0_WDATA;
output  [127:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [1023:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [56:0] sext_ln33;
output  [5:0] bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_address0;
output   bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_ce0;
output   bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_we0;
output  [783:0] bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_d0;
output  [5:0] bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_address0;
output   bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_ce0;
output   bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_we0;
output  [783:0] bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_d0;
output  [5:0] bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_address0;
output   bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_ce0;
output   bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_we0;
output  [783:0] bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_d0;
output  [5:0] bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_address0;
output   bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_ce0;
output   bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_we0;
output  [783:0] bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_d0;

reg ap_idle;
reg m_axi_gmem0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln33_fu_147_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln33_fu_159_p1;
reg   [1:0] trunc_ln33_reg_211;
reg   [1:0] trunc_ln33_reg_211_pp0_iter1_reg;
reg   [5:0] lshr_ln_reg_215;
reg   [5:0] lshr_ln_reg_215_pp0_iter1_reg;
wire   [783:0] trunc_ln36_fu_184_p1;
reg   [783:0] trunc_ln36_reg_220;
wire   [63:0] zext_ln33_fu_188_p1;
reg   [8:0] n_fu_68;
wire   [8:0] add_ln33_fu_153_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_n_3;
reg    bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_we0_local;
reg    bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_ce0_local;
reg    bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_we0_local;
reg    bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_ce0_local;
reg    bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_we0_local;
reg    bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_ce0_local;
reg    bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_we0_local;
reg    bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 n_fu_68 = 9'd0;
#0 ap_done_reg = 1'b0;
end

bnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln33_fu_147_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            n_fu_68 <= add_ln33_fu_153_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_68 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        lshr_ln_reg_215 <= {{ap_sig_allocacmp_n_3[7:2]}};
        lshr_ln_reg_215_pp0_iter1_reg <= lshr_ln_reg_215;
        trunc_ln33_reg_211 <= trunc_ln33_fu_159_p1;
        trunc_ln33_reg_211_pp0_iter1_reg <= trunc_ln33_reg_211;
        trunc_ln36_reg_220 <= trunc_ln36_fu_184_p1;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_147_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_n_3 = 9'd0;
    end else begin
        ap_sig_allocacmp_n_3 = n_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_ce0_local = 1'b1;
    end else begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln33_reg_211_pp0_iter1_reg == 2'd2))) begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_we0_local = 1'b1;
    end else begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_ce0_local = 1'b1;
    end else begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln33_reg_211_pp0_iter1_reg == 2'd1))) begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_we0_local = 1'b1;
    end else begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_ce0_local = 1'b1;
    end else begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln33_reg_211_pp0_iter1_reg == 2'd0))) begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_we0_local = 1'b1;
    end else begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_ce0_local = 1'b1;
    end else begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln33_reg_211_pp0_iter1_reg == 2'd3))) begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_we0_local = 1'b1;
    end else begin
        bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln33_fu_153_p2 = (ap_sig_allocacmp_n_3 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (m_axi_gmem0_RVALID == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_address0 = zext_ln33_fu_188_p1;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_ce0 = bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_ce0_local;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_d0 = trunc_ln36_reg_220;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_we0 = bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_we0_local;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_address0 = zext_ln33_fu_188_p1;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_ce0 = bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_ce0_local;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_d0 = trunc_ln36_reg_220;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_we0 = bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_we0_local;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_address0 = zext_ln33_fu_188_p1;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_ce0 = bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_ce0_local;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_d0 = trunc_ln36_reg_220;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_we0 = bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_we0_local;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_address0 = zext_ln33_fu_188_p1;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_ce0 = bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_ce0_local;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_d0 = trunc_ln36_reg_220;

assign bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_we0 = bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_we0_local;

assign icmp_ln33_fu_147_p2 = ((ap_sig_allocacmp_n_3 == 9'd256) ? 1'b1 : 1'b0);

assign m_axi_gmem0_ARADDR = 64'd0;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 32'd0;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_ARVALID = 1'b0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 1024'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 128'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign trunc_ln33_fu_159_p1 = ap_sig_allocacmp_n_3[1:0];

assign trunc_ln36_fu_184_p1 = m_axi_gmem0_RDATA[783:0];

assign zext_ln33_fu_188_p1 = lshr_ln_reg_215_pp0_iter1_reg;

endmodule //bnn_top_bnn_top_Pipeline_L1_LOAD
