# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitRepos/EECE4632/Project/phase3_vivado/bnn_minst/bnn_minst.srcs/sources_1/bd/bnn_top/ip/bnn_top_xbar_0/bnn_top_xbar_0.xci
# IP: The module: 'bnn_top_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitRepos/EECE4632/Project/phase3_vivado/bnn_minst/bnn_minst.gen/sources_1/bd/bnn_top/ip/bnn_top_xbar_0/bnn_top_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bnn_top_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/GitRepos/EECE4632/Project/phase3_vivado/bnn_minst/bnn_minst.srcs/sources_1/bd/bnn_top/ip/bnn_top_xbar_0/bnn_top_xbar_0.xci
# IP: The module: 'bnn_top_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitRepos/EECE4632/Project/phase3_vivado/bnn_minst/bnn_minst.gen/sources_1/bd/bnn_top/ip/bnn_top_xbar_0/bnn_top_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bnn_top_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
