# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitRepos/MNISTBNN/Project/phase3_vivado/bnn_top/bnn_top.srcs/sources_1/bd/bnn_top/ip/bnn_top_bnn_top_0_0/bnn_top_bnn_top_0_0.xci
# IP: The module: 'bnn_top_bnn_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitRepos/MNISTBNN/Project/phase3_vivado/bnn_top/bnn_top.gen/sources_1/bd/bnn_top/ip/bnn_top_bnn_top_0_0/constraints/bnn_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bnn_top_bnn_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/GitRepos/MNISTBNN/Project/phase3_vivado/bnn_top/bnn_top.srcs/sources_1/bd/bnn_top/ip/bnn_top_bnn_top_0_0/bnn_top_bnn_top_0_0.xci
# IP: The module: 'bnn_top_bnn_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitRepos/MNISTBNN/Project/phase3_vivado/bnn_top/bnn_top.gen/sources_1/bd/bnn_top/ip/bnn_top_bnn_top_0_0/constraints/bnn_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bnn_top_bnn_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
