// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_top_bnn_top_Pipeline_RECV_INPUT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_stream_TVALID,
        input_stream_TDATA,
        input_stream_TREADY,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TLAST,
        input_out,
        input_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   input_stream_TVALID;
input  [31:0] input_stream_TDATA;
output   input_stream_TREADY;
input  [3:0] input_stream_TKEEP;
input  [3:0] input_stream_TSTRB;
input  [0:0] input_stream_TLAST;
output  [783:0] input_out;
output   input_out_ap_vld;

reg ap_idle;
reg input_stream_TREADY;
reg input_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln55_fu_106_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    input_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [4:0] i_1_reg_315;
reg   [0:0] icmp_ln55_reg_322;
reg   [0:0] icmp_ln55_reg_322_pp0_iter1_reg;
reg   [31:0] empty_reg_326_0;
reg   [31:0] empty_reg_326_pp0_iter1_reg_0;
wire   [9:0] lo_fu_123_p3;
reg   [9:0] lo_reg_331;
wire   [9:0] hi_fu_142_p3;
reg   [9:0] hi_reg_339;
wire   [31:0] lshr_ln64_fu_164_p2;
reg   [31:0] lshr_ln64_reg_345;
wire   [0:0] icmp_ln64_fu_170_p2;
reg   [0:0] icmp_ln64_reg_350;
reg   [0:0] icmp_ln64_reg_350_pp0_iter2_reg;
wire   [783:0] shl_ln64_fu_227_p2;
reg   [783:0] shl_ln64_reg_358;
wire   [783:0] and_ln64_1_fu_245_p2;
reg   [783:0] and_ln64_1_reg_364;
reg   [783:0] input_fu_66;
wire   [783:0] input_1_fu_285_p2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [4:0] i_fu_70;
wire   [4:0] i_2_fu_112_p2;
reg   [4:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln63_fu_130_p2;
wire   [9:0] or_ln_fu_135_p3;
wire   [4:0] trunc_ln64_fu_150_p1;
wire   [4:0] xor_ln64_fu_154_p2;
wire   [31:0] zext_ln64_1_fu_160_p1;
wire   [31:0] and_ln64_fu_179_p2;
wire   [9:0] sub_ln64_fu_188_p2;
wire   [9:0] select_ln64_fu_193_p3;
wire   [9:0] select_ln64_2_fu_203_p3;
wire   [9:0] select_ln64_1_fu_198_p3;
wire   [9:0] sub_ln64_1_fu_209_p2;
wire   [783:0] zext_ln64_fu_184_p1;
wire   [783:0] zext_ln64_2_fu_215_p1;
wire   [783:0] zext_ln64_3_fu_219_p1;
wire   [783:0] zext_ln64_4_fu_223_p1;
wire   [783:0] shl_ln64_1_fu_233_p2;
wire   [783:0] lshr_ln64_1_fu_239_p2;
reg   [783:0] tmp_fu_254_p4;
wire   [783:0] xor_ln64_1_fu_269_p2;
wire   [783:0] select_ln64_3_fu_263_p3;
wire   [783:0] and_ln64_2_fu_274_p2;
wire   [783:0] and_ln64_3_fu_280_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 input_fu_66 = 784'd0;
#0 i_fu_70 = 5'd0;
#0 ap_done_reg = 1'b0;
end

bnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln55_fu_106_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            i_fu_70 <= i_2_fu_112_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_70 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            input_fu_66 <= 784'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            input_fu_66 <= input_1_fu_285_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln64_1_reg_364 <= and_ln64_1_fu_245_p2;
        icmp_ln64_reg_350_pp0_iter2_reg <= icmp_ln64_reg_350;
        shl_ln64_reg_358 <= shl_ln64_fu_227_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_reg_326_0 <= input_stream_TDATA;
        empty_reg_326_pp0_iter1_reg_0 <= empty_reg_326_0;
        hi_reg_339[9 : 4] <= hi_fu_142_p3[9 : 4];
        i_1_reg_315 <= ap_sig_allocacmp_i_1;
        icmp_ln55_reg_322 <= icmp_ln55_fu_106_p2;
        icmp_ln55_reg_322_pp0_iter1_reg <= icmp_ln55_reg_322;
        icmp_ln64_reg_350 <= icmp_ln64_fu_170_p2;
        lo_reg_331[9 : 5] <= lo_fu_123_p3[9 : 5];
        lshr_ln64_reg_345 <= lshr_ln64_fu_164_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln55_fu_106_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_70;
    end
end

always @ (*) begin
    if (((icmp_ln55_reg_322_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        input_out_ap_vld = 1'b1;
    end else begin
        input_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln55_fu_106_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_stream_TDATA_blk_n = input_stream_TVALID;
    end else begin
        input_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln55_fu_106_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_stream_TREADY = 1'b1;
    end else begin
        input_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln64_1_fu_245_p2 = (shl_ln64_1_fu_233_p2 & lshr_ln64_1_fu_239_p2);

assign and_ln64_2_fu_274_p2 = (xor_ln64_1_fu_269_p2 & input_fu_66);

assign and_ln64_3_fu_280_p2 = (select_ln64_3_fu_263_p3 & and_ln64_1_reg_364);

assign and_ln64_fu_179_p2 = (lshr_ln64_reg_345 & empty_reg_326_pp0_iter1_reg_0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln55_fu_106_p2 == 1'd0) & (input_stream_TVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign hi_fu_142_p3 = ((icmp_ln63_fu_130_p2[0:0] == 1'b1) ? or_ln_fu_135_p3 : 10'd783);

assign i_2_fu_112_p2 = (ap_sig_allocacmp_i_1 + 5'd1);

assign icmp_ln55_fu_106_p2 = ((ap_sig_allocacmp_i_1 == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln63_fu_130_p2 = ((i_1_reg_315 < 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_170_p2 = ((lo_fu_123_p3 > hi_fu_142_p3) ? 1'b1 : 1'b0);

assign input_1_fu_285_p2 = (and_ln64_3_fu_280_p2 | and_ln64_2_fu_274_p2);

assign input_out = input_fu_66;

assign lo_fu_123_p3 = {{i_1_reg_315}, {5'd0}};

assign lshr_ln64_1_fu_239_p2 = 784'd101745825697019260773923519755878567461315282017759829107608914364075275235254395622580447400994175578963163918967182013639660669771108475957692810857098847138903161308502419410142185759152435680068435915159402496058513611411689167650815 >> zext_ln64_4_fu_223_p1;

assign lshr_ln64_fu_164_p2 = 32'd4294967295 >> zext_ln64_1_fu_160_p1;

assign or_ln_fu_135_p3 = {{i_1_reg_315}, {5'd31}};

assign select_ln64_1_fu_198_p3 = ((icmp_ln64_reg_350[0:0] == 1'b1) ? hi_reg_339 : lo_reg_331);

assign select_ln64_2_fu_203_p3 = ((icmp_ln64_reg_350[0:0] == 1'b1) ? sub_ln64_fu_188_p2 : lo_reg_331);

assign select_ln64_3_fu_263_p3 = ((icmp_ln64_reg_350_pp0_iter2_reg[0:0] == 1'b1) ? tmp_fu_254_p4 : shl_ln64_reg_358);

assign select_ln64_fu_193_p3 = ((icmp_ln64_reg_350[0:0] == 1'b1) ? lo_reg_331 : hi_reg_339);

assign shl_ln64_1_fu_233_p2 = 784'd101745825697019260773923519755878567461315282017759829107608914364075275235254395622580447400994175578963163918967182013639660669771108475957692810857098847138903161308502419410142185759152435680068435915159402496058513611411689167650815 << zext_ln64_3_fu_219_p1;

assign shl_ln64_fu_227_p2 = zext_ln64_fu_184_p1 << zext_ln64_2_fu_215_p1;

assign sub_ln64_1_fu_209_p2 = ($signed(10'd783) - $signed(select_ln64_fu_193_p3));

assign sub_ln64_fu_188_p2 = ($signed(10'd783) - $signed(lo_reg_331));

integer ap_tvar_int_0;

always @ (shl_ln64_reg_358) begin
    for (ap_tvar_int_0 = 784 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 783 - 0) begin
            tmp_fu_254_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_fu_254_p4[ap_tvar_int_0] = shl_ln64_reg_358[783 - ap_tvar_int_0];
        end
    end
end

assign trunc_ln64_fu_150_p1 = hi_fu_142_p3[4:0];

assign xor_ln64_1_fu_269_p2 = (784'd101745825697019260773923519755878567461315282017759829107608914364075275235254395622580447400994175578963163918967182013639660669771108475957692810857098847138903161308502419410142185759152435680068435915159402496058513611411689167650815 ^ and_ln64_1_reg_364);

assign xor_ln64_fu_154_p2 = (trunc_ln64_fu_150_p1 ^ 5'd31);

assign zext_ln64_1_fu_160_p1 = xor_ln64_fu_154_p2;

assign zext_ln64_2_fu_215_p1 = select_ln64_2_fu_203_p3;

assign zext_ln64_3_fu_219_p1 = select_ln64_1_fu_198_p3;

assign zext_ln64_4_fu_223_p1 = sub_ln64_1_fu_209_p2;

assign zext_ln64_fu_184_p1 = and_ln64_fu_179_p2;

always @ (posedge ap_clk) begin
    lo_reg_331[4:0] <= 5'b00000;
    hi_reg_339[3:0] <= 4'b1111;
end

endmodule //bnn_top_bnn_top_Pipeline_RECV_INPUT
