

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_3_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_2_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_1_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l1_weights_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l2_weights_3_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l2_weights_2_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l2_weights_1_U"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_local_l2_weights_U"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.local_l3_weights_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l1_output_U"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l1_output_1_U"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l2_output_U"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l2_output_1_U"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_RECV_INPUT_fu_4611"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_RECV_INPUT_fu_4611.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_NEURON_fu_4624"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_NEURON_fu_4624.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_NEURON_fu_4639"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_NEURON_fu_4639.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_NEURON_fu_4654"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_NEURON_fu_4654.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_LOAD_fu_4669"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_LOAD_fu_4669.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_LOAD_fu_4684"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_LOAD_fu_4684.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_LOAD_fu_4699"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_LOAD_fu_4699.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem2_m_axi_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_data_V_U"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_keep_V_U"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_strb_V_U"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_last_V_U"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_data_V_U"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_keep_V_U"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_strb_V_U"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_last_V_U"}]}
set DependenceCheckSize 0
